tasks:
  - command: /opt/bin/entry_point.sh & /opt/novnc/utils/launch.sh --vnc "localhost:5900" --listen "6080" & npm i && mkdir -p /workspace/test-with-gitpod/node_modules/selenium-standalone/.selenium/chromedriver/ && ln -s /usr/bin/chromedriver /workspace/test-with-gitpod/node_modules/selenium-standalone/.selenium/chromedriver/81.0.4044.69-x64-chromedriver && npm run compile -- -w & echo -e "You are ready! \nRun your test by 'npm run test'"
  
image:
  file: .gitpod.Dockerfile

ports:
  - port: 6080
    onOpen: open-browser
  - port: 1-6079
    onOpen: ignore
  - port: 6081-65535
    onOpen: ignore

vscode:
  extensions:
    - LogiGear.gondola-studio@1.5.519:g7UcBWe40SBZqF/ACzFihA==
