tasks:
  - init: echo "Replace me with a build script for the project."
    command: echo "Replace me with something that should run on every start, or just
      remove me entirely."
image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - LogiGear.gondola-studio@1.5.519:g7UcBWe40SBZqF/ACzFihA==