tasks:
  - command: /opt/bin/entry_point.sh &
  - command: cd /opt/novnc/utils && ./launch.sh --vnc "localhost:5900" --listen "6080" &
  - command: npm i && echo "Run your test by `npm run test`"
  
image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - LogiGear.gondola-studio@1.5.519:g7UcBWe40SBZqF/ACzFihA==
