tasks:
  - command: /opt/bin/entry_point.sh &
  - command: cd /opt/novnc/utils && ./launch.sh --vnc "localhost:5900" --listen "6080" &
  - command: npm i && npm run compile && echo -e "\n\n\nRun your test by 'npm run test'"
  
image:
  file: .gitpod.Dockerfile

ports:
  - port: 6080
    onOpen: open-browser
  - port: 4444
    onOpen: ignore
  - port: 5900
    onOpen: ignore
  - port: 8080
    onOpen: ignore

vscode:
  extensions:
    - LogiGear.gondola-studio@1.5.519:g7UcBWe40SBZqF/ACzFihA==
