tasks:
  - init: echo "Replace me with a build script for the project."
    command: cd /opt/novnc/utils && ./launch.sh --vnc "localhost:5900" --listen "6080" & \
            /opt/bin/entry_point.sh &
image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - LogiGear.gondola-studio@1.5.519:g7UcBWe40SBZqF/ACzFihA==
